# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            wong2
tagline:          ''
description:      '这里要有一句很文艺的话'
url:              http://blog.wong2.me

author:
  name:           'wong2'
  url:            http://wong2.me

paginate:         5
